version: 2

before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - 386
    - arm
    - arm64

  ignore:
    - goos: darwin
      goarch: '386'
    - goos: windows
      goarch: 'arm'

  ldflags:
    - -s -w

  binary: '{{ .ProjectName }}'

archives:
- formats:
    - zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true
