name: GoReleaser

on:
  push:
    tags:
      - "*"

jobs:

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Clean dist directory
        run: rm -rf dist

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.8.1
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}